<script lang="ts">
  import DashboardContent from '$lib/components/DashboardContent.svelte';
  import CommunicationComposer from '$lib/components/CommunicationComposer.svelte';
  import { Button } from '$lib/components/ui/button/index.js';
  import { Plus, MessageSquare, Pencil, Trash2, Search } from 'lucide-svelte';
  import { goto } from '$app/navigation';
  const { data } = $props();
  const students=$derived(data.students??[]); const pagination=$derived(data.pagination??{}); const templates=$derived(data.messageTemplates??[]);
  let messageOpen=$state(false); let messageIds=$state<string[]>([]); let messageSample=$state<any>(students[0]??{});
  let search=$state(pagination.search??''); let balance=$state(pagination.balance??'all'); let status=$state(pagination.status??'all');
  function apply(){const p=new URLSearchParams();if(search)p.set('search',search);if(balance!=='all')p.set('balance',balance);if(status!=='all')p.set('status',status);goto(`?${p}`);}
  function messageOne(s:any){messageIds=[s.id];messageSample={...s,parent_name:'Parent'};messageOpen=true;}
  function messageAll(){messageIds=students.map((s:any)=>s.id);messageSample={...(students[0]??{}),parent_name:'Parent'};messageOpen=true;}
</script>
<DashboardContent title="Students" subtitle="Filter the roster, take actions, and communicate with parents or guardians.">
  {#snippet headerActions()}<Button href="/admin/students/import" size="sm" variant="outline">Import</Button><Button size="sm"><Plus class="h-3.5 w-3.5"/> Add Student</Button>{/snippet}
  <div class="space-y-5">
    <section class="rounded-xl border border-slate-200/70 bg-white p-4 shadow-sm"><form onsubmit={(e)=>{e.preventDefault();apply();}} class="grid gap-3 md:grid-cols-[1fr_180px_160px_auto]"><label class="relative"><span class="sr-only">Search</span><Search class="absolute left-3 top-3 h-4 w-4 text-slate-400"/><input bind:value={search} class="min-h-10 w-full rounded-lg border border-slate-200 pl-9 pr-3 text-sm" placeholder="Name, admission no, class..."/></label><select bind:value={balance} class="min-h-10 rounded-lg border border-slate-200 px-3 text-sm"><option value="all">All balances</option><option value="outstanding">Has balance</option><option value="clear">No balance</option></select><select bind:value={status} class="min-h-10 rounded-lg border border-slate-200 px-3 text-sm"><option value="all">All status</option><option value="active">Active</option><option value="inactive">Inactive</option></select><Button type="submit">Apply</Button></form></section>
    <section class="rounded-xl border border-slate-200/70 bg-white shadow-sm overflow-hidden"><div class="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 px-5 py-4"><div><h2 class="text-base font-bold text-slate-900">{pagination.total??students.length} students</h2><p class="mt-1 text-xs text-slate-500">Current filter: {balance==='outstanding'?'students with balances':balance==='clear'?'students with no balance':'all balances'}.</p></div><button type="button" onclick={messageAll} disabled={!students.length} class="inline-flex min-h-10 items-center gap-2 rounded-lg bg-primary px-4 text-sm font-bold text-primary-foreground disabled:opacity-50"><MessageSquare class="h-4 w-4"/> Message Parents · {students.length}</button></div>
      <div class="overflow-x-auto"><table class="w-full text-sm"><thead class="bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-3">Admission</th><th class="px-5 py-3">Student</th><th class="px-5 py-3">Class</th><th class="px-5 py-3">Balance</th><th class="px-5 py-3">Status</th><th class="px-5 py-3 text-right">Actions</th></tr></thead><tbody class="divide-y divide-slate-100">{#each students as s}<tr class="hover:bg-slate-50/70"><td class="px-5 py-3 font-medium">{s.admission_no}</td><td class="px-5 py-3 font-semibold">{s.first_name} {s.last_name}</td><td class="px-5 py-3">{s.grade??'—'}</td><td class="px-5 py-3 font-semibold {Number(s.balance)>0?'text-amber-700':'text-emerald-700'}">KES {Number(s.balance??0).toLocaleString()}</td><td class="px-5 py-3">{s.status}</td><td class="px-5 py-3"><div class="flex justify-end gap-1"><button title="Message parent" type="button" onclick={()=>messageOne(s)} class="rounded-lg p-2 hover:bg-slate-100"><MessageSquare class="h-4 w-4"/></button><button title="Edit" type="button" class="rounded-lg p-2 hover:bg-slate-100"><Pencil class="h-4 w-4"/></button><button title="Delete" type="button" class="rounded-lg p-2 text-red-600 hover:bg-red-50"><Trash2 class="h-4 w-4"/></button></div></td></tr>{:else}<tr><td colspan="6" class="px-5 py-12 text-center text-sm text-slate-500">No students match these filters.</td></tr>{/each}</tbody></table></div>
    </section>
  </div>
</DashboardContent>
<CommunicationComposer bind:open={messageOpen} recipientLabel="parent messages" recipientCount={messageIds.length} recipientIds={messageIds} templates={templates} sample={messageSample} />
