<script lang="ts">
  import TrendChart from '$lib/components/charts/TrendChart.svelte';
  import DonutChart from '$lib/components/charts/DonutChart.svelte';
  const { data }: { data: any } = $props();
  const money=(v:number)=>`KES ${Number(v||0).toLocaleString()}`;
  const reportLinks=[['Students','Student population, classes and lifecycle','/admin/students'],['Admissions','Applications and admission pipeline','/admin/sis/admissions'],['Attendance','Attendance trends and class breakdowns','/admin/attendance'],['Finance','Collections, payments and balances','/admin/finance'],['ReClass','Remedial participation and delivery','/admin/reclass'],['Payroll','Staff and remedial payroll activity','/admin/payroll']];
</script>
<svelte:head><title>Reports · eShule</title><meta name="description" content="Interactive eShule school reports and operational insights." /></svelte:head>
<div class="mx-auto max-w-[1500px] space-y-6 px-4 py-5 sm:px-6 lg:px-8">
  <header class="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p class="text-xs font-bold uppercase tracking-[.16em] text-primary">Insights</p><h1 class="mt-1 text-2xl font-bold tracking-tight text-slate-950 sm:text-3xl">Reports</h1><p class="mt-1 text-sm text-slate-500">Understand what is happening across students, attendance, finance and programmes.</p></div><div class="flex gap-2">{#each [7,30,90,365] as d}<a class={`rounded-lg border px-3 py-2 text-xs font-semibold ${data.days===d?'border-primary bg-primary text-primary-foreground':'border-slate-200 bg-white text-slate-600 hover:bg-slate-50'}`} href={`?days=${d}`}>{d===365?'Year':`${d} days`}</a>{/each}</div></header>
  <section class="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{#each [{l:'Students',v:data.kpis.students},{l:'Active enrolments',v:data.kpis.active},{l:'Admissions',v:data.kpis.admissions},{l:'Collections',v:money(data.kpis.collected)},{l:'Attendance',v:`${data.kpis.attendanceRate.toFixed(1)}%`}] as k}<div class="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><p class="text-xs font-semibold text-slate-500">{k.l}</p><p class="mt-2 text-2xl font-bold tracking-tight text-slate-950">{k.v}</p><p class="mt-1 text-[11px] text-slate-400">Selected period</p></div>{/each}</section>
  <section class="grid gap-5 xl:grid-cols-[1.7fr_1fr]"><article class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div class="flex items-start justify-between"><div><h2 class="font-bold text-slate-950">Attendance</h2><p class="mt-1 text-xs text-slate-500">Present and absent records over time</p></div><a href="/admin/attendance" class="text-xs font-semibold text-primary">Open →</a></div><div class="mt-4"><TrendChart data={data.attendanceTrend} primaryLabel="Present" secondaryLabel="Absent" /></div></article><article class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="font-bold text-slate-950">Students by class</h2><p class="mt-1 text-xs text-slate-500">Current student population</p><div class="mt-4"><DonutChart data={data.studentMix} centerLabel="Students" centerValue={String(data.kpis.students)} /></div></article></section>
  <section class="grid gap-5 xl:grid-cols-[1.7fr_1fr]"><article class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div class="flex items-start justify-between"><div><h2 class="font-bold text-slate-950">Collections trend</h2><p class="mt-1 text-xs text-slate-500">Payment activity during the selected period</p></div><a href="/admin/finance" class="text-xs font-semibold text-primary">Finance →</a></div><div class="mt-4"><TrendChart data={data.paymentTrend} primaryLabel="Payment value (KES)" /></div></article><article class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="font-bold text-slate-950">Admissions pipeline</h2><p class="mt-1 text-xs text-slate-500">Application outcomes</p><div class="mt-4"><DonutChart data={data.admissionMix} centerLabel="Applications" centerValue={String(data.kpis.admissions)} /></div></article></section>
  <section><div class="mb-3"><h2 class="text-lg font-bold text-slate-950">Report areas</h2><p class="mt-1 text-sm text-slate-500">Open an operational area for detailed records and exports.</p></div><div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{#each reportLinks as r}<a href={r[2]} class="group rounded-xl border border-slate-200 bg-white p-4 shadow-sm transition hover:-translate-y-0.5 hover:border-primary/40 hover:shadow-md"><div class="flex items-center justify-between"><h3 class="text-sm font-bold text-slate-900 group-hover:text-primary">{r[0]}</h3><span class="text-slate-300 group-hover:text-primary">→</span></div><p class="mt-1 text-xs leading-5 text-slate-500">{r[1]}</p></a>{/each}</div></section>
</div>
