<script lang="ts">
  import DashboardContent from '$lib/components/DashboardContent.svelte';
  import { CalendarDays, CheckCircle2, Clock3, Plus, Archive, ArrowRight } from 'lucide-svelte';
  import type { PageData } from './$types';
  const { data }: { data: PageData } = $props();
  interface Session { id: string; title: string; subject: string; grade: string; teacher: string; day_of_week: number; start_time: string; end_time: string; slot: string | null; room: string | null; active: boolean; }
  interface Option { id: string; name: string; }
  const subjects: Option[] = $derived(data.subjects ?? []);
  const teachers: Option[] = $derived(data.teachers ?? []);
  const sessions: Session[] = $derived(data.schedules ?? []);
  const activeSessions = $derived(sessions.filter((s) => s.active));
  const inactiveSessions = $derived(sessions.filter((s) => !s.active));
  const dayLabels = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];
  const dayOptions = dayLabels.map((l, i) => ({ value: i + 1, label: l }));
  const dbDayToIndex = (d: number) => d - 1;
  let currentMonth = $state(new Date().getMonth()); let currentYear = $state(new Date().getFullYear());
  const daysInMonth = $derived(new Date(currentYear, currentMonth + 1, 0).getDate());
  const monthStartOffset = $derived((new Date(currentYear, currentMonth, 1).getDay() + 6) % 7);
  const monthLabel = $derived(new Date(currentYear, currentMonth).toLocaleDateString('en', { month: 'long', year: 'numeric' }));
  const calendarCells = $derived(Array.from({ length: 42 }, (_, index) => { const day = index - monthStartOffset + 1; return day > 0 && day <= daysInMonth ? day : null; }));
  const sessionsByDay = $derived.by(() => { const map: Record<number, Session[]> = {}; for (const s of sessions) { if (!map[s.day_of_week]) map[s.day_of_week] = []; map[s.day_of_week].push(s); } return map; });
  function getSessionsForDay(day: number) { const date = new Date(currentYear, currentMonth, day); const dbDay = ((date.getDay() + 6) % 7) + 1; return sessionsByDay[dbDay] ?? []; }
  function timeDisplay(t: string) { if (!t) return '—'; const [hRaw, m = '00'] = t.split(':'); const h = parseInt(hRaw, 10); return `${h % 12 || 12}:${m} ${h >= 12 ? 'PM' : 'AM'}`; }
  let showForm = $state(false); let newClass = $state(''); let newSubject = $state(''); let newTeacher = $state(''); let newDay = $state('1'); let newStart = $state('14:00'); let newEnd = $state('15:00'); let newRoom = $state(''); const newSlot = $state('');
  function confirmDelete(e: Event) { if (!confirm('Archive this recurring session? Existing attendance and payment evidence will not be deleted.')) e.preventDefault(); }
</script>
<svelte:head><title>ReClass scheduling · eShule</title><meta name="description" content="Schedule and manage recurring remedial sessions." /></svelte:head>
<DashboardContent title="ReClass scheduling" subtitle="Create the recurring session first; delivery, attendance and learner outcomes follow from the schedule.">
  {#snippet headerActions()}<div class="flex flex-wrap items-center gap-2"><button type="button" onclick={() => showForm = !showForm} class="ui-action ui-action-primary"><Plus class="h-4 w-4" /> {showForm ? 'Close' : 'Add session'}</button><button type="button" aria-label="Previous month" onclick={() => { currentMonth === 0 ? (currentMonth = 11, currentYear--) : currentMonth--; }} class="ui-action ui-action-secondary">← Prev</button><span class="px-1 text-sm font-semibold text-foreground">{monthLabel}</span><button type="button" aria-label="Next month" onclick={() => { currentMonth === 11 ? (currentMonth = 0, currentYear++) : currentMonth++; }} class="ui-action ui-action-secondary">Next →</button></div>{/snippet}

  <div class="grid gap-3 sm:grid-cols-3 mb-6"><div class="ui-card p-4"><p class="text-xs text-ink-400">Active programme</p><p class="mt-1 text-2xl font-bold text-ink-900">{activeSessions.length}</p><p class="mt-1 text-xs text-ink-400">Recurring sessions</p></div><div class="ui-card p-4"><p class="text-xs text-ink-400">Paused</p><p class="mt-1 text-2xl font-bold text-ink-900">{inactiveSessions.length}</p><p class="mt-1 text-xs text-ink-400">Not currently scheduled for delivery</p></div><div class="ui-status ui-status-info h-full"><CalendarDays class="h-4 w-4" /><span>Schedule → deliver → attendance → learner outcome</span></div></div>

  {#if showForm}<form method="POST" action="?/create" class="mb-6 ui-card border-primary/20 bg-primary/5 p-5"><input type="hidden" name="slot" value={newSlot} /><div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div><label for="session-class" class="mb-1 block text-xs font-semibold text-ink-600">Class</label><input id="session-class" name="class" bind:value={newClass} required placeholder="e.g. Form 2" class="ui-control w-full" /></div><div><label for="session-subject" class="mb-1 block text-xs font-semibold text-ink-600">Subject</label><select id="session-subject" name="subject_id" bind:value={newSubject} required class="ui-control w-full"><option value="">Select subject…</option>{#each subjects as s}<option value={s.id}>{s.name}</option>{/each}</select></div><div><label for="session-teacher" class="mb-1 block text-xs font-semibold text-ink-600">Teacher</label><select id="session-teacher" name="teacher_id" bind:value={newTeacher} required class="ui-control w-full"><option value="">Select teacher…</option>{#each teachers as t (t.id)}<option value={t.id}>{t.name}</option>{/each}</select></div><div><label for="session-room" class="mb-1 block text-xs font-semibold text-ink-600">Room</label><input id="session-room" name="room" bind:value={newRoom} required placeholder="e.g. Lab 2" class="ui-control w-full" /></div><div><label for="session-day" class="mb-1 block text-xs font-semibold text-ink-600">Day</label><select id="session-day" name="day_of_week" bind:value={newDay} class="ui-control w-full">{#each dayOptions as o}<option value={o.value}>{o.label}</option>{/each}</select></div><div><label for="session-start" class="mb-1 block text-xs font-semibold text-ink-600">Start</label><input id="session-start" type="time" name="start_time" bind:value={newStart} class="ui-control w-full" /></div><div><label for="session-end" class="mb-1 block text-xs font-semibold text-ink-600">End</label><input id="session-end" type="time" name="end_time" bind:value={newEnd} class="ui-control w-full" /></div><div class="flex items-end"><button type="submit" class="ui-action ui-action-primary min-h-11 w-full justify-center">Save recurring session <ArrowRight class="h-4 w-4" /></button></div></div></form>{/if}

  <div class="ui-card mb-6 overflow-hidden"><div class="grid grid-cols-7 border-b border-border bg-slate-50">{#each dayLabels as label}<div class="px-2 py-2.5 text-center text-[11px] font-medium uppercase tracking-[0.12em] text-slate-500">{label}</div>{/each}</div><div class="grid grid-cols-7">{#each calendarCells as day, index}{@const daySessions = day ? getSessionsForDay(day) : []}{@const isToday = day === new Date().getDate() && currentMonth === new Date().getMonth() && currentYear === new Date().getFullYear()}<div class="min-h-28 border-b border-r border-border p-1.5 {index % 7 === 6 ? 'border-r-0' : ''} {day ? 'bg-white' : 'bg-slate-50'}">{#if day}<span class="mb-1 inline-flex h-6 w-6 items-center justify-center rounded-full text-xs font-medium {isToday ? 'bg-primary text-primary-foreground' : 'text-muted-foreground'}">{day}</span>{#if daySessions.length > 0}<div class="space-y-1">{#each daySessions.slice(0, 3) as session}<div class="truncate rounded px-1.5 py-1 text-[10px] font-medium leading-tight {session.active ? 'bg-primary/10 text-primary' : 'bg-muted text-muted-foreground'}" title="{session.title} · {session.subject} · {timeDisplay(session.start_time)}–{timeDisplay(session.end_time)}">{session.title}<span class="block text-[9px]">{timeDisplay(session.start_time)}</span></div>{/each}{#if daySessions.length > 3}<div class="text-center text-[9px] font-medium text-muted-foreground">+{daySessions.length - 3} more</div>{/if}</div>{/if}{/if}</div>{/each}</div></div>

  <section class="ui-card overflow-hidden"><div class="border-b border-border bg-slate-50 px-4 py-3"><div class="flex items-center justify-between"><div><h2 class="text-sm font-semibold text-foreground">Recurring sessions</h2><p class="mt-1 text-xs text-muted-foreground">These sessions generate the delivery work teachers complete.</p></div><span class="ui-status ui-status-info">{sessions.length} total</span></div></div><div class="divide-y divide-border/70">{#each sessions as session}<article class="p-4 sm:p-5"><div class="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div class="min-w-0"><div class="flex flex-wrap items-center gap-2"><h3 class="text-sm font-semibold text-foreground">{session.title}</h3><span class="ui-status {session.active ? 'ui-status-success' : 'ui-status-warning'}">{session.active ? 'Active' : 'Paused'}</span></div><p class="mt-1 text-sm text-muted-foreground">{dayLabels[dbDayToIndex(session.day_of_week)]} · {timeDisplay(session.start_time)}–{timeDisplay(session.end_time)} · {session.subject}</p><p class="mt-1 text-xs text-muted-foreground">Teacher: {session.teacher || 'Unassigned'} · {session.room || 'Room not set'}</p></div><div class="grid w-full grid-cols-2 gap-2 sm:flex sm:w-auto"><form method="POST" action="?/toggle" class="contents"><input type="hidden" name="id" value={session.id} /><input type="hidden" name="active" value={session.active ? 'false' : 'true'} /><button type="submit" class="ui-action ui-action-secondary min-h-11 justify-center">{session.active ? 'Pause' : 'Activate'}</button></form><form method="POST" action="?/delete" class="contents"><input type="hidden" name="id" value={session.id} /><button type="submit" onclick={confirmDelete} class="ui-action ui-action-danger min-h-11 justify-center"><Archive class="h-4 w-4" /> Archive</button></form></div></div></article>{:else}<div class="p-10 text-center"><CalendarDays class="mx-auto h-8 w-8 text-ink-300" /><p class="mt-3 text-sm font-semibold text-ink-700">No sessions scheduled</p><p class="mt-1 text-xs text-ink-400">Create the first recurring session to start the ReClass delivery workflow.</p></div>{/each}</div></section>
</DashboardContent>