<script lang="ts">
 import DashboardContent from '$lib/components/DashboardContent.svelte'; import DataTable from '$lib/components/DataTable.svelte'; import CommunicationComposer from '$lib/components/CommunicationComposer.svelte'; import { Button } from '$lib/components/ui/button/index.js'; import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogFooter,DialogClose } from '$lib/components/ui/dialog/index.js'; import { Plus,MessageSquare,Trash2 } from 'lucide-svelte'; import { enhance } from '$app/forms';
 const {data}= $props(); const teachers=$derived(data.teachers??[]); const templates=$derived(data.messageTemplates??[]); let messageOpen=$state(false); let ids=$state<string[]>([]); let sample=$state<any>({}); let search=$state(data.filters?.search??''); let role=$state(data.filters?.role??'all'); let editing=$state<any>(null); let deleting=$state<any>(null);
 function apply(){const p=new URLSearchParams();if(search)p.set('search',search);if(role!=='all')p.set('role',role);window.location.href=`?${p}`;}
 function message(t:any){ids=[t.id];sample=t;messageOpen=true;} function messageAll(){ids=teachers.map((t:any)=>t.id);sample=teachers[0]??{};messageOpen=true;}
 function openEdit(t:any){editing=t;} function openDelete(t:any){deleting=t;}
</script>
<DashboardContent title="Teachers" subtitle="Manage teaching staff, filters and direct communication.">
 {#snippet headerActions()}<Button onclick={messageAll} size="sm" variant="outline" disabled={!teachers.length}><MessageSquare class="h-3.5 w-3.5"/> Message {teachers.length} teachers</Button><Button onclick={()=>editing={}} size="sm"><Plus class="h-3.5 w-3.5"/> Add Teacher</Button>{/snippet}
 <div class="space-y-5"><section class="rounded-xl border border-slate-200 bg-white p-4"><form onsubmit={(e)=>{e.preventDefault();apply();}} class="grid gap-3 md:grid-cols-[1fr_200px_auto]"><input bind:value={search} class="min-h-10 rounded-lg border border-slate-200 px-3 text-sm" placeholder="Search teacher, employee no, subject..."/><select bind:value={role} class="min-h-10 rounded-lg border border-slate-200 px-3 text-sm"><option value="all">All committee roles</option><option value="chairman">Chairman</option><option value="treasurer">Treasurer</option><option value="member">Member</option><option value="none">No committee role</option></select><Button type="submit">Apply</Button></form></section>
 <DataTable data={teachers} columns={[{key:'first_name',label:'Name',render:(t:any)=>`${t.first_name} ${t.last_name}`,sortable:true},{key:'employee_no',label:'Employee No',sortable:true},{key:'subjects',label:'Subjects',render:(t:any)=>t.subjects?.join(', ')??'—'},{key:'remedial_role',label:'Committee',render:(t:any)=>t.remedial_role??'none'},{key:'phone',label:'Payment phone',render:(t:any)=>t.phone??'—'}]} emptyMessage="No teachers match these filters" onEdit={openEdit} onDelete={openDelete}>
  {#snippet rowExtra(t)}<button type="button" title="Message teacher" onclick={()=>message(t)} class="inline-flex items-center gap-1 rounded-lg border border-slate-200 px-2.5 py-1.5 text-xs font-semibold text-slate-700 hover:bg-slate-50"><MessageSquare class="h-3.5 w-3.5"/> Message</button>{/snippet}
 </DataTable></div>
</DashboardContent>
<CommunicationComposer bind:open={messageOpen} recipientLabel="teachers" recipientCount={ids.length} recipientIds={ids} recipientField="teacher_ids" templates={templates} sample={sample} action="?/messageTeachers"/>
<Dialog open={!!editing} onOpenChange={(v:boolean)=>{if(!v)editing=null}}><DialogContent class="sm:max-w-lg"><DialogHeader><DialogTitle>{editing?.id?'Edit Teacher':'Add Teacher'}</DialogTitle></DialogHeader><form method="POST" action={editing?.id?'?/update':'?/create'} use:enhance class="space-y-4"><input type="hidden" name="id" value={editing?.id??''}/><div class="grid grid-cols-2 gap-3"><input name="first_name" required value={editing?.first_name??''} placeholder="First name" class="rounded-lg border p-2.5 text-sm"/><input name="last_name" required value={editing?.last_name??''} placeholder="Last name" class="rounded-lg border p-2.5 text-sm"/></div><input name="employee_no" value={editing?.employee_no??''} placeholder="Employee no" class="w-full rounded-lg border p-2.5 text-sm"/><input name="subjects" value={editing?.subjects?.join(', ')??''} placeholder="Subjects" class="w-full rounded-lg border p-2.5 text-sm"/><input name="phone" value={editing?.phone??''} placeholder="M-Pesa phone" class="w-full rounded-lg border p-2.5 text-sm"/><select name="remedial_role" value={editing?.remedial_role??'none'} class="w-full rounded-lg border p-2.5 text-sm"><option value="none">No committee role</option><option value="chairman">Chairman</option><option value="treasurer">Treasurer</option><option value="member">Member</option></select><DialogFooter><DialogClose><button type="button" class="rounded-lg border px-4 py-2 text-sm">Cancel</button></DialogClose><Button type="submit">Save</Button></DialogFooter></form></DialogContent></Dialog>
<Dialog open={!!deleting} onOpenChange={(v:boolean)=>{if(!v)deleting=null}}><DialogContent class="sm:max-w-sm"><div class="p-2 text-center"><Trash2 class="mx-auto h-8 w-8 text-red-600"/><h3 class="mt-3 font-bold">Delete teacher?</h3><p class="mt-2 text-sm text-slate-500">This deactivates {deleting?.first_name} {deleting?.last_name}.</p><form method="POST" action="?/delete" use:enhance class="mt-5"><input type="hidden" name="id" value={deleting?.id??''}/><Button type="submit" variant="destructive">Delete</Button></form></div></DialogContent></Dialog>
