<script lang="ts">
 import DashboardContent from '$lib/components/DashboardContent.svelte';
 const {data}= $props();
 const money=(v:number)=>`KES ${Number(v||0).toLocaleString()}`;
 const maxAtt=Math.max(1,...(data.attendance??[]).map((d:any)=>Number(d.total||0)));
 const maxPay=Math.max(1,...(data.payments??[]).map((p:any)=>Number(p.amount||0)));
</script>
<DashboardContent title="Analytics" subtitle="Live operational data from school transactions and teacher attendance.">
 {#snippet headerActions()}<div class="flex gap-2"><a href="?days=7" class="rounded-lg border px-3 py-2 text-xs font-semibold">7 days</a><a href="?days=30" class="rounded-lg border px-3 py-2 text-xs font-semibold">30 days</a><a href="?days=90" class="rounded-lg border px-3 py-2 text-xs font-semibold">90 days</a></div>{/snippet}
 <div class="space-y-6">
  <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{#each [["Collections",money(data.kpis.collected)],['Outstanding',money(data.kpis.outstanding)],['Paid transactions',data.kpis.paidTransactions],['Teacher attendance',`${data.kpis.attendanceRate.toFixed(1)}%`]] as k}<section class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs font-semibold uppercase tracking-wide text-slate-500">{k[0]}</p><p class="mt-2 text-2xl font-bold text-slate-950">{k[1]}</p></section>{/each}</div>
  <div class="grid gap-6 lg:grid-cols-2">
   <section class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="font-bold">Teacher attendance trend</h2><p class="mt-1 text-xs text-slate-500">Attended vs absent sessions · {data.days} days</p><div class="mt-6 flex h-56 items-end gap-2 overflow-x-auto">{#each data.attendance as d}<div class="flex min-w-7 flex-1 flex-col items-center gap-1"><div class="w-full rounded-t bg-primary/70" style={`height:${Math.max(4,Number(d.attended)/maxAtt*180)}px`} title={`Attended ${d.attended}`}></div><div class="w-full rounded-t bg-red-200" style={`height:${Math.max(2,Number(d.absent)/maxAtt*180)}px`} title={`Absent ${d.absent}`}></div><span class="text-[9px] text-slate-400">{String(d.day).slice(5)}</span></div>{:else}<p class="m-auto text-sm text-slate-500">No attendance data for this period.</p>{/each}</div><div class="mt-3 flex gap-4 text-xs"><span>■ Attended</span><span>■ Absent</span></div></section>
   <section class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="font-bold">Payment activity</h2><p class="mt-1 text-xs text-slate-500">Successful and pending school-fee transactions</p><div class="mt-6 space-y-3">{#each data.payments.slice(-10) as p}<div><div class="flex justify-between text-xs"><span>{new Date(p.created_at).toLocaleDateString()}</span><strong>{money(p.amount)}</strong></div><div class="mt-1 h-2 overflow-hidden rounded bg-slate-100"><div class="h-full rounded bg-primary" style={`width:${Math.max(4,Number(p.amount)/maxPay*100)}%`}></div></div></div>{:else}<p class="py-12 text-center text-sm text-slate-500">No payment transactions for this period.</p>{/each}</div></section>
  </div>
  <section class="rounded-xl border border-slate-200 bg-white shadow-sm overflow-hidden"><div class="border-b px-5 py-4"><h2 class="font-bold">Weekly payroll</h2></div><div class="overflow-x-auto"><table class="w-full text-sm"><thead class="bg-slate-50 text-left text-xs text-slate-500"><tr><th class="px-5 py-3">Period</th><th class="px-5 py-3">Teachers</th><th class="px-5 py-3">Payroll</th><th class="px-5 py-3">Paid</th><th class="px-5 py-3">Confirmed</th></tr></thead><tbody class="divide-y">{#each data.payroll as p}<tr><td class="px-5 py-3">{p.period_start} – {p.period_end}</td><td class="px-5 py-3">{p.teacher_count}</td><td class="px-5 py-3 font-semibold">{money(p.payroll_total)}</td><td class="px-5 py-3">{p.paid_teachers}</td><td class="px-5 py-3">{p.confirmed_teachers}</td></tr>{:else}<tr><td colspan="5" class="px-5 py-10 text-center text-slate-500">No payroll records yet.</td></tr>{/each}</tbody></table></div></section>
 </div>
</DashboardContent>
