<script lang="ts">
 import TrendChart from '$lib/components/charts/TrendChart.svelte';
 import DonutChart from '$lib/components/charts/DonutChart.svelte';
 import DashboardContent from '$lib/components/DashboardContent.svelte';
 const {data}: {data:any}= $props();
 const money=(v:number)=>`KES ${Number(v||0).toLocaleString()}`;
 const admissionsMix = data.admissionsMix ?? [{label:'Paid',value:data.kpis.paidTransactions ?? 0},{label:'Other',value:Math.max(0,(data.kpis.invoices ?? 0)-(data.kpis.paidTransactions ?? 0))}];
</script>
<DashboardContent title="Analytics" subtitle="Interactive operational intelligence for students, attendance, finance and payroll.">
 {#snippet headerActions()}<div class="flex gap-2">{#each [7,30,90] as d}<a class={`rounded-lg border px-3 py-2 text-xs font-semibold ${data.days===d?'border-primary bg-primary text-primary-foreground':'border-slate-200 bg-white text-slate-600'}`} href={`?days=${d}`}>{d} days</a>{/each}</div>{/snippet}
 <div class="space-y-5">
  <div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
   {#each [{l:'Collections',v:money(data.kpis.collected)},{l:'Outstanding',v:money(data.kpis.outstanding)},{l:'Paid transactions',v:data.kpis.paidTransactions},{l:'Teacher attendance',v:`${data.kpis.attendanceRate.toFixed(1)}%`}] as k}<section class="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><p class="text-xs font-semibold text-slate-500">{k.l}</p><p class="mt-2 text-2xl font-bold tracking-tight text-slate-950">{k.v}</p></section>{/each}
  </div>
  <div class="grid gap-5 xl:grid-cols-[1.6fr_1fr]">
   <section class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div class="flex items-start justify-between"><div><h2 class="font-bold text-slate-950">Attendance trend</h2><p class="mt-1 text-xs text-slate-500">Attended vs absent · last {data.days} days</p></div><span class="rounded-full bg-slate-100 px-2.5 py-1 text-[11px] font-semibold text-slate-600">Live</span></div><div class="mt-4"><TrendChart data={(data.attendance ?? []).map((d:any)=>({label:String(d.day).slice(5),value:Number(d.attended||0),secondary:Number(d.absent||0)}))} primaryLabel="Attended" secondaryLabel="Absent" /></div></section>
   <section class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="font-bold text-slate-950">Attendance mix</h2><p class="mt-1 text-xs text-slate-500">Share of recorded teacher attendance</p><div class="mt-4"><DonutChart data={[{label:'Attended',value:data.kpis.attendanceRate ? Math.round(data.kpis.attendanceRate) : 0},{label:'Absent',value:data.kpis.attendanceRate ? Math.max(0,100-Math.round(data.kpis.attendanceRate)) : 0}]} centerLabel="Rate" centerValue={`${data.kpis.attendanceRate.toFixed(0)}%`} /></div></section>
  </div>
  <div class="grid gap-5 xl:grid-cols-[1.6fr_1fr]">
   <section class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div class="flex items-start justify-between"><div><h2 class="font-bold text-slate-950">Payment trend</h2><p class="mt-1 text-xs text-slate-500">Transaction value over time</p></div><a href="/admin/finance" class="text-xs font-semibold text-primary">Open finance →</a></div><div class="mt-4"><TrendChart data={(data.payments ?? []).slice(-14).map((p:any)=>({label:String(p.created_at).slice(5,10),value:Number(p.amount||0)}))} primaryLabel="Payment value (KES)" /></div></section>
   <section class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="font-bold text-slate-950">Finance position</h2><p class="mt-1 text-xs text-slate-500">Invoice ledger for the selected school</p><div class="mt-5"><DonutChart data={[{label:'Collected',value:Number(data.kpis.invoices||0)-Number(data.kpis.outstanding||0)},{label:'Outstanding',value:Number(data.kpis.outstanding||0)}]} centerLabel="Invoice value" centerValue={money(data.kpis.invoices||0)} /></div></section>
  </div>
  <section class="rounded-xl border border-slate-200 bg-white shadow-sm"><div class="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><h2 class="font-bold text-slate-950">Payroll trend</h2><p class="mt-1 text-xs text-slate-500">Weekly payroll, teachers and confirmations</p></div></div><div class="overflow-x-auto"><table class="w-full min-w-[680px] text-sm"><thead class="bg-slate-50 text-left text-xs text-slate-500"><tr><th class="px-5 py-3">Period</th><th class="px-5 py-3">Teachers</th><th class="px-5 py-3">Payroll</th><th class="px-5 py-3">Paid</th><th class="px-5 py-3">Confirmed</th></tr></thead><tbody class="divide-y">{#each (data.payroll as any[]) as p}<tr><td class="px-5 py-3">{p.period_start} – {p.period_end}</td><td class="px-5 py-3">{p.teacher_count}</td><td class="px-5 py-3 font-semibold">{money(p.payroll_total)}</td><td class="px-5 py-3">{p.paid_teachers}</td><td class="px-5 py-3">{p.confirmed_teachers}</td></tr>{:else}<tr><td colspan="5" class="px-5 py-10 text-center text-slate-400">No payroll records yet.</td></tr>{/each}</tbody></table></div></section>
 </div>
</DashboardContent>
