<script lang="ts">
 import DashboardContent from '$lib/components/DashboardContent.svelte'; import { Button } from '$lib/components/ui/button/index.js'; import { Plus } from 'lucide-svelte'; import { enhance } from '$app/forms'; import { dispatchToast } from '$lib/notifications';
 const { data } = $props(); let open = $state(false); let submitting = $state(false); const events = $derived(data.events);
 function submit(){submitting=true;return async({result,update}:any)=>{if(result.type==='success'){open=false;dispatchToast('Saved',result.data?.message??'Saved')}else if(result.type==='failure')dispatchToast('Error',result.data?.message??'Could not save');await update();submitting=false;}}
</script>
<DashboardContent title="School Calendar" subtitle="Academic dates, meetings, holidays, ReClass sessions and operational reminders">
{#snippet headerActions()}<Button size="sm" onclick={()=>open=true}><Plus class="h-3.5 w-3.5"/> Add Event</Button>{/snippet}
<div class="space-y-3">{#each events as e}<div class="flex items-center justify-between rounded-xl border border-border bg-white p-4"><div class="flex items-start gap-4"><div class="min-w-16 rounded-lg bg-primary/10 px-3 py-2 text-center"><p class="text-lg font-bold text-primary">{new Date(e.starts_at).getDate()}</p><p class="text-[10px] uppercase text-muted-foreground">{new Date(e.starts_at).toLocaleString('en',{month:'short'})}</p></div><div><p class="text-sm font-semibold">{e.title}</p><p class="mt-1 text-xs capitalize text-muted-foreground">{e.event_type} · {e.audience}{e.location?` · ${e.location}`:''}</p><p class="mt-1 text-xs text-muted-foreground">{new Date(e.starts_at).toLocaleString()}</p></div></div><form method="POST" action="?/delete" use:enhance><input type="hidden" name="id" value={e.id}/><button class="text-xs text-muted-foreground hover:text-destructive">Remove</button></form></div>{:else}<div class="rounded-xl border border-dashed border-border p-12 text-center text-sm text-muted-foreground">No calendar events yet.</div>{/each}</div>
</DashboardContent>
{#if open}<div class="fixed inset-0 z-50 flex items-center justify-center bg-black/30 p-4"><div class="w-full max-w-lg rounded-2xl bg-white shadow-xl"><div class="border-b px-6 py-4"><h2 class="font-semibold">Add Calendar Event</h2></div><form method="POST" action="?/create" use:enhance={submit} class="grid gap-4 px-6 py-5"><label class="text-xs font-medium">Title<input name="title" required class="field"/></label><label class="text-xs font-medium">Type<select name="event_type" class="field"><option value="event">Event</option><option value="holiday">Holiday</option><option value="meeting">Meeting</option><option value="reclass">ReClass</option><option value="deadline">Deadline</option><option value="other">Other</option></select></label><label class="text-xs font-medium">Starts<input name="starts_at" type="datetime-local" required class="field"/></label><label class="text-xs font-medium">Ends<input name="ends_at" type="datetime-local" class="field"/></label><label class="text-xs font-medium">Location<input name="location" class="field"/></label><label class="text-xs font-medium">Audience<select name="audience" class="field"><option value="school">School</option><option value="teachers">Teachers</option><option value="students">Students</option><option value="parents">Parents</option><option value="admin">Admin</option></select></label><label class="text-xs font-medium">Description<textarea name="description" rows="3" class="field"></textarea></label><div class="flex justify-end gap-2"><Button type="button" variant="outline" onclick={()=>open=false}>Cancel</Button><Button type="submit" disabled={submitting}>Create Event</Button></div></form></div></div>{/if}
<style>:global(.field){width:100%;margin-top:.3rem;border:1px solid hsl(var(--border));border-radius:.5rem;padding:.55rem .7rem;font-size:.875rem;outline:none}</style>
