import { z } from 'zod/v3';
import { fail } from '@sveltejs/kit';
import type { PageServerLoad, Actions } from './$types';
import { requireTenantRole } from '$lib/server/_auth/auth';
import { parseForm } from '$lib/server/_platform/validation';

const schema = z.object({ title: z.string().min(1).max(200), description: z.string().max(2000).optional(), event_type: z.enum(['holiday','meeting','reclass','deadline','event','other']), starts_at: z.string().min(1), ends_at: z.string().optional(), location: z.string().max(200).optional(), audience: z.enum(['school','teachers','students','parents','admin']) });
export const load: PageServerLoad = async ({ locals }) => { const { tenantId } = requireTenantRole(locals, 'school_admin', 'super_admin'); const db = locals.srv as unknown as { from: (table: string) => any }; const { data: events } = await db.from('school_calendar_events').select('id,title,description,event_type,starts_at,ends_at,all_day,location,audience').eq('tenant_id', tenantId).is('deleted_at', null).order('starts_at', { ascending: true }).limit(300); return { events: events ?? [] }; };
export const actions = { create: async ({ locals, request }) => { const { tenantId } = requireTenantRole(locals, 'school_admin', 'super_admin'); const v = parseForm(schema, await request.formData()); if (!v.success) return fail(400, { errors: v.errors }); const db = locals.srv as unknown as { from: (table: string) => any }; const { error } = await db.from('school_calendar_events').insert({ tenant_id: tenantId, title: v.data.title.trim(), description: v.data.description || null, event_type: v.data.event_type, starts_at: v.data.starts_at, ends_at: v.data.ends_at || null, location: v.data.location || null, audience: v.data.audience, created_by: locals.user?.id || null }); if (error) return fail(500, { message: error.message }); return { success: true, message: 'Calendar event created.' }; }, delete: async ({ locals, request }) => { const { tenantId } = requireTenantRole(locals, 'school_admin', 'super_admin'); const fd = await request.formData(); const id = String(fd.get('id') ?? ''); if (!id) return fail(400, { message: 'Event ID required.' }); const db = locals.srv as unknown as { from: (table: string) => any }; const { error } = await db.from('school_calendar_events').update({ deleted_at: new Date().toISOString() }).eq('id', id).eq('tenant_id', tenantId); if (error) return fail(500, { message: error.message }); return { success: true, message: 'Calendar event removed.' }; } } satisfies Actions;
