<script lang="ts">
  const { runs = [], components = [] } = $props();
  const editableRuns = $derived(runs.filter((r: any) => r.status === 'draft' || r.status === 'pending'));
  const typeLabels: Record<string, string> = { base_salary: 'Base salary', allowance: 'Allowance', remedial: 'Remedial payment', committee: 'Committee payment', role_specific: 'Role-specific payment', adjustment: 'Adjustment' };
</script>
<section class="rounded-xl border border-slate-200 bg-white p-6 shadow-sm">
  <div class="mb-5"><h2 class="text-base font-semibold text-slate-900">Compensation components</h2><p class="mt-1 text-sm text-slate-500">Build payroll from transparent, separately auditable payment lines.</p></div>
  <form method="POST" action="?/addComponent" class="grid grid-cols-1 gap-3 md:grid-cols-2 lg:grid-cols-4">
    <label class="text-xs font-medium text-slate-600">Payroll run<select name="payroll_run_id" required class="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm"><option value="">Select run</option>{#each editableRuns as run}<option value={run.id}>{run.teacher_name} · {run.period_start}–{run.period_end}</option>{/each}</select></label>
    <label class="text-xs font-medium text-slate-600">Payment type<select name="component_type" required class="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm">{#each Object.entries(typeLabels) as [value,label]}<option {value}>{label}</option>{/each}</select></label>
    <label class="text-xs font-medium text-slate-600">Description<input name="description" required placeholder="e.g. Principal responsibility" class="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm" /></label>
    <label class="text-xs font-medium text-slate-600">Quantity<input name="quantity" type="number" min="0.01" step="0.01" value="1" required class="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm" /></label>
    <label class="text-xs font-medium text-slate-600">Rate (KES)<input name="rate" type="number" min="0" step="0.01" required class="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm" /></label>
    <label class="text-xs font-medium text-slate-600">Amount (KES)<input name="amount" type="number" min="0" step="0.01" required class="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm" /></label>
    <label class="text-xs font-medium text-slate-600">Role code<input name="role_code" placeholder="principal" class="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm" /></label>
    <label class="text-xs font-medium text-slate-600">Role label<input name="role_label" placeholder="Principal" class="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm" /></label>
    <div class="md:col-span-2 lg:col-span-4"><button class="rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white hover:bg-blue-700" type="submit">Add compensation line</button></div>
  </form>
  <div class="mt-6 overflow-x-auto"><table class="min-w-full text-sm"><thead><tr class="border-b text-left text-xs text-slate-500"><th class="px-3 py-2">Type</th><th class="px-3 py-2">Description</th><th class="px-3 py-2">Role</th><th class="px-3 py-2">Qty</th><th class="px-3 py-2">Rate</th><th class="px-3 py-2">Amount</th></tr></thead><tbody>{#each components as c}<tr class="border-b border-slate-100"><td class="px-3 py-2">{typeLabels[c.component_type] ?? c.component_type}</td><td class="px-3 py-2">{c.description}</td><td class="px-3 py-2">{c.role_label || '—'}</td><td class="px-3 py-2">{c.quantity}</td><td class="px-3 py-2">KES {Number(c.rate).toLocaleString()}</td><td class="px-3 py-2 font-semibold">KES {Number(c.amount).toLocaleString()}</td></tr>{/each}{#if components.length === 0}<tr><td colspan="6" class="px-3 py-8 text-center text-sm text-slate-500">No compensation lines yet.</td></tr>{/if}</tbody></table></div>
</section>