<script lang="ts">
  import TrendChart from '$lib/components/charts/TrendChart.svelte';
  import DonutChart from '$lib/components/charts/DonutChart.svelte';
  const { data }: { data: any } = $props();
  const money=(v:number)=>`KES ${Number(v||0).toLocaleString()}`;
  const kpi=[['Students','students','/admin/students'],['Active enrolments','activeStudents','/admin/students'],['Admissions','admissions','/admin/sis/admissions'],['Collections','collected','/admin/finance'],['Attendance','attendanceRate','/admin/attendance']];
</script>
<svelte:head><title>Dashboard · eShule</title><meta name="description" content="eShule school operations dashboard." /></svelte:head>
<div class="mx-auto max-w-[1500px] space-y-6 px-4 py-5 sm:px-6 lg:px-8">
  <header class="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-xs font-bold uppercase tracking-[.16em] text-primary">School overview</p><h1 class="mt-1 text-2xl font-bold tracking-tight text-slate-950 sm:text-3xl">Dashboard</h1><p class="mt-1 text-sm text-slate-500">Your school's operational pulse for the last {data.days} days.</p></div><div class="flex gap-2">{#each [7,30,90] as d}<a class={`rounded-lg border px-3 py-2 text-xs font-semibold ${data.days===d?'border-primary bg-primary text-primary-foreground':'border-slate-200 bg-white text-slate-600 hover:bg-slate-50'}`} href={`?days=${d}`}>{d} days</a>{/each}</div></header>
  <section class="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{#each kpi as card}<a href={card[2]} class="rounded-xl border border-slate-200 bg-white p-4 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><p class="text-xs font-semibold text-slate-500">{card[0]}</p><p class="mt-2 text-2xl font-bold tracking-tight text-slate-950">{card[1]==='collected'?money(data.kpis[card[1]]):card[1]==='attendanceRate'?`${data.kpis[card[1]].toFixed(1)}%`:data.kpis[card[1]]}</p><span class="mt-2 block text-[11px] font-semibold text-primary">View details →</span></a>{/each}</section>
  <section class="grid gap-4 xl:grid-cols-[1.65fr_1fr]"><div class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div class="flex items-start justify-between"><div><h2 class="font-bold text-slate-950">Attendance trend</h2><p class="mt-1 text-xs text-slate-500">Teacher attendance across the selected period</p></div><a href="/admin/reports" class="text-xs font-semibold text-primary">Full report →</a></div><div class="mt-4"><TrendChart data={data.attendanceTrend} primaryLabel="Attended" secondaryLabel="Absent" /></div></div><div class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="font-bold text-slate-950">Admissions</h2><p class="mt-1 text-xs text-slate-500">Applications created in this period</p><div class="mt-5"><DonutChart data={data.admissionMix ?? []} centerLabel="Applications" /></div></div></section>
  <section class="grid gap-4 lg:grid-cols-2"><div class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div class="flex items-start justify-between"><div><h2 class="font-bold text-slate-950">Payment activity</h2><p class="mt-1 text-xs text-slate-500">Recent school-fee transactions</p></div><a href="/admin/finance" class="text-xs font-semibold text-primary">Finance →</a></div><div class="mt-4"><TrendChart data={data.paymentTrend ?? []} primaryLabel="Payment amount (KES)" /></div></div><div class="rounded-xl border border-slate-200 bg-white shadow-sm"><div class="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><h2 class="font-bold text-slate-950">Recent payments</h2><p class="mt-1 text-xs text-slate-500">Latest activity</p></div><a href="/admin/finance" class="text-xs font-semibold text-primary">View all →</a></div><div class="divide-y divide-slate-100">{#each data.recentPayments ?? [] as p}<div class="flex items-center justify-between px-5 py-3"><div><p class="text-sm font-medium text-slate-800">{p.method ?? 'Payment'}</p><p class="text-xs text-slate-400">{String(p.created_at).slice(0,10)}</p></div><strong class="text-sm text-slate-950">{money(p.amount)}</strong></div>{:else}<p class="px-5 py-10 text-center text-sm text-slate-400">No recent payments.</p>{/each}</div></div></section>
  <section><div class="mb-3"><h2 class="text-lg font-bold text-slate-950">Today's work</h2><p class="mt-1 text-sm text-slate-500">Jump directly into the areas that keep the school moving.</p></div><div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{#each [['Students','Admissions, enrolment and lifecycle','/admin/students'],['ReClass','Remedial programmes and attendance','/admin/reclass'],['Calendar','School events and lessons','/admin/calendar'],['Reports','Interactive operational insights','/admin/reports']] as item}<a href={item[2]} class="rounded-lg border border-slate-200 bg-white p-4 shadow-sm transition hover:-translate-y-0.5 hover:border-primary/40 hover:bg-primary/[.03]"><p class="text-sm font-semibold text-slate-900">{item[0]}</p><p class="mt-1 text-xs leading-5 text-slate-500">{item[1]}</p></a>{/each}</div></section>
</div>
