-- Payroll state transitions are server-side and auditable.
create or replace function public.submit_payroll_for_principal(p_payroll_id uuid)
returns public.payroll_periods language plpgsql security definer set search_path=public as $$
declare p public.payroll_periods; ok boolean; begin select * into p from public.payroll_periods where id=p_payroll_id for update;if not found then raise exception 'Payroll not found';end if;select exists(select 1 from public.payroll_committee_members where tenant_id=p.tenant_id and user_id=auth.uid() and active) into ok;if not ok then raise exception 'Only an assigned payroll committee member can submit payroll';end if;if p.status not in ('draft','returned') then raise exception 'Payroll is not editable at this stage';end if;update public.payroll_periods set status='submitted',submitted_by=auth.uid(),submitted_at=now() where id=p.id returning * into p;insert into public.audit_logs(actor_user_id,action,module,entity_type,entity_id,source,result,metadata)values(auth.uid(),'payroll_submitted','payroll','payroll_period',p.id,'web','success',jsonb_build_object('period_start',p.period_start,'period_end',p.period_end));return p;end;$$;

create or replace function public.approve_payroll_by_principal(p_payroll_id uuid,p_note text default null)
returns public.payroll_periods language plpgsql security definer set search_path=public as $$
declare p public.payroll_periods; ok boolean; begin select * into p from public.payroll_periods where id=p_payroll_id for update;if not found then raise exception 'Payroll not found';end if;select exists(select 1 from public.user_roles where tenant_id=p.tenant_id and user_id=auth.uid() and role='principal') into ok;if not ok then raise exception 'Only the principal can approve payroll';end if;if p.status<>'submitted' then raise exception 'Payroll must be submitted before principal approval';end if;update public.payroll_periods set status='principal_approved',principal_approved_by=auth.uid(),principal_approved_at=now(),return_reason=null where id=p.id returning * into p;insert into public.audit_logs(actor_user_id,action,module,entity_type,entity_id,source,result,metadata)values(auth.uid(),'payroll_principal_approved','payroll','payroll_period',p.id,'web','success',jsonb_build_object('note',p_note));return p;end;$$;

create or replace function public.initiate_payroll_payment(p_payment_id uuid)
returns public.payroll_payments language plpgsql security definer set search_path=public as $$
declare p public.payroll_payments; pr public.payroll_periods; ok boolean;begin select * into p from public.payroll_payments where id=p_payment_id for update;if not found then raise exception 'Payment not found';end if;select * into pr from public.payroll_periods where id=p.payroll_id;if pr.status<>'principal_approved' then raise exception 'Payroll must have principal approval first';end if;select exists(select 1 from public.payroll_committee_members where tenant_id=pr.tenant_id and user_id=auth.uid() and active and rights @> '["initiate_payments"]'::jsonb) into ok;if not ok then raise exception 'User is not an authorized payment initiator';end if;update public.payroll_payments set status='initiated',initiated_by=auth.uid(),initiated_at=now() where id=p.id and status='pending' returning * into p;if p.id is null then raise exception 'Payment is not pending';end if;insert into public.audit_logs(actor_user_id,action,module,entity_type,entity_id,target_user_id,source,result,metadata)values(auth.uid(),'payment_initiated','payroll','payroll_payment',p.id,p.teacher_user_id,'web','success',jsonb_build_object('amount',p.amount));return p;end;$$;

-- Payment approval is restricted to an assigned payment approver and cannot be self-approved.
create or replace function public.finalize_payroll_payment_approval(p_payment_id uuid)
returns public.payroll_payments language plpgsql security definer set search_path=public as $$
declare p public.payroll_payments; pr public.payroll_periods; r public.payment_receipts; ok boolean; template_id uuid;begin select * into p from public.payroll_payments where id=p_payment_id for update;if not found then raise exception 'Payment not found';end if;if p.status<>'initiated' then raise exception 'Payment must be initiated before approval';end if;if p.initiated_by=auth.uid() then raise exception 'Payment initiator cannot approve the same payment';end if;select * into pr from public.payroll_periods where id=p.payroll_id;select exists(select 1 from public.payroll_committee_members where tenant_id=pr.tenant_id and user_id=auth.uid() and active and rights @> '["approve_payments"]'::jsonb) into ok;if not ok then raise exception 'User is not an authorized payment approver';end if;update public.payroll_payments set status='approved',approved_by=auth.uid(),approved_at=now() where id=p.id returning * into p;insert into public.payment_receipts(tenant_id,payment_id,payment_domain,recipient_user_id,teacher_user_id,amount,receipt_number,payment_reference,payment_method,confirmation_status,metadata)values(pr.tenant_id,p.id,'payroll',p.teacher_user_id,p.teacher_user_id,p.amount,public.next_payment_receipt_number(),p.payment_reference,'payroll','pending',jsonb_build_object('payroll_id',p.payroll_id))on conflict(payment_id)do nothing returning * into r;select id into template_id from public.notification_templates where key='PAYMENT_APPROVED_TEACHER' and channel='in_app' and active=true order by version desc limit 1;if template_id is not null then insert into public.notifications(tenant_id,event_key,template_id,recipient_user_id,channel,status,subject,body,entity_type,entity_id,triggered_by_user_id,metadata)values(pr.tenant_id,'PAYMENT_APPROVED_TEACHER',template_id,p.teacher_user_id,'in_app','queued','Payroll payment approved','Your payroll payment of KES '||to_char(p.amount,'FM999,999,990.00')||' has been approved. Once the funds reach you, confirm receipt in eShule.','payroll_payment',p.id,auth.uid(),jsonb_build_object('receipt_id',r.id,'receipt_number',r.receipt_number));end if;insert into public.audit_logs(actor_user_id,action,module,entity_type,entity_id,target_user_id,source,result,metadata)values(auth.uid(),'payment_approved','payroll','payroll_payment',p.id,p.teacher_user_id,'web','success',jsonb_build_object('receipt_id',r.id,'amount',p.amount));return p;end;$$;

-- Generate an individual school-fee receipt immediately when a successful payment is reconciled.
create or replace function public.reconcile_payment(p_checkout_id text,p_amount numeric,p_phone text,p_tenant_id uuid)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_invoice_id uuid;v_payment_id uuid;v_student_id uuid;begin
 select id,student_id into v_invoice_id,v_student_id from public.invoices where tenant_id=p_tenant_id and status in('unpaid','partial') order by due_date asc nulls last limit 1 for update skip locked;
 if not found then return jsonb_build_object('status','no_pending_invoice');end if;
 insert into public.payments(invoice_id,tenant_id,amount,phone,method,mpesa_checkout_id,status)values(v_invoice_id,p_tenant_id,p_amount,p_phone,'mpesa',p_checkout_id,'paid')on conflict(mpesa_checkout_id)do update set status='paid',updated_at=now() returning id into v_payment_id;
 update public.invoices set status=case when(amount_paid+p_amount)>=amount_due then 'paid' else 'partial' end,amount_paid=amount_paid+p_amount where id=v_invoice_id;
 insert into public.payment_receipts(tenant_id,payment_id,payment_domain,payer_user_id,student_id,amount,receipt_number,payment_reference,payment_method,paid_at,confirmation_status,metadata)values(p_tenant_id,v_payment_id,'school_fee',null,v_student_id,p_amount,public.next_payment_receipt_number(),p_checkout_id,'mpesa',now(),'not_required','{"source":"reconcile_payment"}'::jsonb)on conflict(payment_id)do nothing;
 return jsonb_build_object('status','completed','invoice_id',v_invoice_id,'payment_id',v_payment_id,'receipt_id',(select id from public.payment_receipts where payment_id=v_payment_id));
exception when unique_violation then return jsonb_build_object('status','duplicate','checkout_id',p_checkout_id);end;$$;
