alter table public.reclass_fee_definition drop constraint if exists reclass_fee_definition_amount_check;
alter table public.reclass_fee_definition add constraint reclass_fee_definition_amount_check check (amount > 0);
alter table public.reclass_fee_definition add constraint reclass_fee_definition_effective_dates_check check (effective_to is null or effective_from is null or effective_to >= effective_from);
alter table public.reclass_obligations add constraint reclass_obligations_period_dates_check check (period_end is null or period_start is null or period_end >= period_start);
alter table public.reclass_obligations add constraint reclass_obligations_paid_amount_lte_amount_check check (paid_amount <= amount);
create unique index if not exists uq_reclass_obligation_student_fee_period on public.reclass_obligations(student_id, fee_definition_id, period_start, period_end) where status <> 'cancelled';

create or replace function public.manage_reclass_fee_definition(p_id uuid,p_name text,p_amount numeric,p_frequency text,p_description text,p_active boolean,p_effective_from date,p_effective_to date) returns jsonb language plpgsql security definer set search_path to 'public' as $$ declare v_id uuid; begin if not public.current_user_has_reclass_permission('reclass.finance.manage') then raise exception 'Not authorized'; end if; if nullif(trim(p_name),'') is null then raise exception 'Fee name is required'; end if; if p_amount is null or p_amount <= 0 then raise exception 'Fee amount must be greater than zero'; end if; if p_frequency not in ('once','weekly','monthly','term','annual') then raise exception 'Invalid fee frequency'; end if; if p_effective_to is not null and p_effective_from is not null and p_effective_to < p_effective_from then raise exception 'Effective end date cannot precede start date'; end if; if p_id is null then insert into public.reclass_fee_definition(name,amount,frequency,description,active,effective_from,effective_to,created_by) values(trim(p_name),p_amount,p_frequency,nullif(trim(p_description),''),coalesce(p_active,true),p_effective_from,p_effective_to,auth.uid()) returning id into v_id; else update public.reclass_fee_definition set name=trim(p_name),amount=p_amount,frequency=p_frequency,description=nullif(trim(p_description),''),active=coalesce(p_active,true),effective_from=p_effective_from,effective_to=p_effective_to where id=p_id returning id into v_id; if v_id is null then raise exception 'Fee definition not found'; end if; end if; return jsonb_build_object('id',v_id); end; $$;

create or replace function public.manage_reclass_obligation(p_id uuid,p_student_id uuid,p_fee_definition_id uuid,p_period_start date,p_period_end date,p_amount numeric,p_status text default 'open') returns jsonb language plpgsql security definer set search_path to 'public' as $$ declare v_id uuid; v_paid numeric; begin if not public.current_user_has_reclass_permission('reclass.finance.manage') then raise exception 'Not authorized'; end if; if p_student_id is null or not exists(select 1 from public.students s where s.id=p_student_id and s.deleted_at is null and coalesce(s.status,'active')='active') then raise exception 'Active student not found'; end if; if not exists(select 1 from public.reclass_fee_definition f where f.id=p_fee_definition_id) then raise exception 'Fee definition not found'; end if; if p_amount is null or p_amount <= 0 then raise exception 'Obligation amount must be greater than zero'; end if; if p_period_end is not null and p_period_start is not null and p_period_end < p_period_start then raise exception 'Period end cannot precede period start'; end if; if p_status not in ('open','partially_paid','paid','waived','cancelled') then raise exception 'Invalid obligation status'; end if; if p_id is null then insert into public.reclass_obligations(student_id,fee_definition_id,period_start,period_end,amount,paid_amount,status,created_by) values(p_student_id,p_fee_definition_id,p_period_start,p_period_end,p_amount,0,p_status,auth.uid()) returning id into v_id; else select paid_amount into v_paid from public.reclass_obligations where id=p_id for update; if v_paid is null then raise exception 'Obligation not found'; end if; if p_amount < v_paid then raise exception 'Amount cannot be below paid amount'; end if; if p_status='open' and v_paid > 0 then p_status := case when v_paid >= p_amount then 'paid' else 'partially_paid' end; end if; update public.reclass_obligations set student_id=p_student_id,fee_definition_id=p_fee_definition_id,period_start=p_period_start,period_end=p_period_end,amount=p_amount,status=p_status where id=p_id returning id into v_id; end if; return jsonb_build_object('id',v_id); end; $$;

create or replace function public.cancel_reclass_obligation(p_obligation_id uuid) returns boolean language plpgsql security definer set search_path to 'public' as $$ begin if not public.current_user_has_reclass_permission('reclass.finance.manage') then raise exception 'Not authorized'; end if; update public.reclass_obligations set status='cancelled' where id=p_obligation_id and status <> 'paid' and paid_amount=0; if not found then raise exception 'Only unpaid non-paid obligations can be cancelled'; end if; return true; end; $$;

revoke execute on function public.manage_reclass_fee_definition(uuid,text,numeric,text,text,boolean,date,date) from public,anon;
grant execute on function public.manage_reclass_fee_definition(uuid,text,numeric,text,text,boolean,date,date) to authenticated;
revoke execute on function public.manage_reclass_obligation(uuid,uuid,uuid,date,date,numeric,text) from public,anon;
grant execute on function public.manage_reclass_obligation(uuid,uuid,uuid,date,date,numeric,text) to authenticated;
revoke execute on function public.cancel_reclass_obligation(uuid) from public,anon;
grant execute on function public.cancel_reclass_obligation(uuid) to authenticated;
