-- Shared audit + notification foundation for eShule/ReClass.
-- NOTE: This migration originally collided with 20260901090000_complete_operations_finance_comms.sql.
-- It has been superseded by the consolidated migration and intentionally contains no schema statements.
