alter table public.sessions drop constraint if exists sessions_time_order_check;
alter table public.sessions add constraint sessions_time_order_check check (end_time > start_time);
alter table public.session_occurrences drop constraint if exists session_occurrences_time_order_check;
alter table public.session_occurrences add constraint session_occurrences_time_order_check check (end_time > start_time);

revoke insert, update, delete, truncate on public.sessions from authenticated;
revoke insert, update, delete, truncate on public.session_occurrences from authenticated;
revoke all on public.sessions from anon;
revoke all on public.session_occurrences from anon;

create or replace function public.manage_reclass_session(p_id uuid,p_day_of_week smallint,p_start_time time,p_end_time time,p_recurrence text,p_active boolean,p_slot text,p_class text,p_subject_id uuid,p_teacher_id uuid,p_room text) returns jsonb language plpgsql security definer set search_path to 'public' as $$ declare v_id uuid; begin if not public.current_user_has_reclass_permission('reclass.programme.manage') then raise exception 'Not authorized'; end if; if p_start_time is null or p_end_time is null or p_end_time <= p_start_time then raise exception 'Session end time must be after start time'; end if; if p_day_of_week is not null and (p_day_of_week < 1 or p_day_of_week > 7) then raise exception 'Invalid day of week'; end if; if p_slot is not null and p_slot not in ('morning','afternoon','evening') then raise exception 'Invalid session slot'; end if; if p_teacher_id is not null and not exists(select 1 from public.teachers t where t.id=p_teacher_id and t.deleted_at is null) then raise exception 'Teacher not found'; end if; if p_id is null then insert into public.sessions(day_of_week,start_time,end_time,recurrence,active,deleted_at,slot,class,subject_id,teacher_id,room,created_at,updated_at) values(p_day_of_week,p_start_time,p_end_time,p_recurrence,coalesce(p_active,true),null,p_slot,p_class,p_subject_id,p_teacher_id,p_room,now(),now()) returning id into v_id; else update public.sessions set day_of_week=p_day_of_week,start_time=p_start_time,end_time=p_end_time,recurrence=p_recurrence,active=coalesce(p_active,true),slot=p_slot,class=p_class,subject_id=p_subject_id,teacher_id=p_teacher_id,room=p_room,updated_at=now() where id=p_id and deleted_at is null returning id into v_id; if v_id is null then raise exception 'Session not found'; end if; end if; return jsonb_build_object('id',v_id); end; $$;

create or replace function public.cancel_reclass_session(p_session_id uuid) returns boolean language plpgsql security definer set search_path to 'public' as $$ begin if not public.current_user_has_reclass_permission('reclass.programme.manage') then raise exception 'Not authorized'; end if; update public.sessions set active=false,deleted_at=coalesce(deleted_at,now()),updated_at=now() where id=p_session_id and deleted_at is null; if not found then raise exception 'Session not found'; end if; update public.session_occurrences set status='cancelled',updated_at=now() where session_id=p_session_id and status='scheduled'; return true; end; $$;

create or replace function public.manage_reclass_session_occurrence(p_id uuid,p_session_id uuid,p_occurs_on date,p_start_time time,p_end_time time,p_room text,p_class text,p_teacher_id uuid,p_status text) returns jsonb language plpgsql security definer set search_path to 'public' as $$ declare v_id uuid; v_session_teacher uuid; v_active boolean; begin if not public.current_user_has_reclass_permission('reclass.programme.manage') then raise exception 'Not authorized'; end if; if p_occurs_on is null or p_start_time is null or p_end_time is null or p_end_time <= p_start_time then raise exception 'Invalid occurrence timing'; end if; if p_status not in ('scheduled','cancelled','done') then raise exception 'Invalid occurrence status'; end if; select s.teacher_id,s.active into v_session_teacher,v_active from public.sessions s where s.id=p_session_id and s.deleted_at is null; if not found or not coalesce(v_active,false) then raise exception 'Active session not found'; end if; if p_teacher_id is distinct from v_session_teacher then raise exception 'Occurrence teacher must match session teacher'; end if; if p_id is null then insert into public.session_occurrences(session_id,occurs_on,start_time,end_time,room,class,teacher_id,status,created_at,updated_at) values(p_session_id,p_occurs_on,p_start_time,p_end_time,p_room,p_class,p_teacher_id,p_status,now(),now()) returning id into v_id; else update public.session_occurrences set session_id=p_session_id,occurs_on=p_occurs_on,start_time=p_start_time,end_time=p_end_time,room=p_room,class=p_class,teacher_id=p_teacher_id,status=p_status,updated_at=now() where id=p_id returning id into v_id; if v_id is null then raise exception 'Occurrence not found'; end if; end if; return jsonb_build_object('id',v_id); end; $$;

create or replace function public.generate_session_occurrences(p_session_id uuid,p_through date default (current_date + 56)) returns integer language plpgsql security definer set search_path to 'public' as $$ declare n integer; begin if not public.current_user_has_reclass_permission('reclass.programme.manage') then raise exception 'Not authorized'; end if; if p_through < current_date then raise exception 'Generation end date cannot be in the past'; end if; insert into public.session_occurrences(session_id,occurs_on,start_time,end_time,room,class,teacher_id,status) select s.id,d::date,s.start_time,s.end_time,s.room,s.class,s.teacher_id,'scheduled' from public.sessions s cross join lateral generate_series(current_date,p_through,interval '1 day') d where s.id=p_session_id and s.active and s.deleted_at is null and extract(isodow from d)::integer=s.day_of_week on conflict(session_id,occurs_on) do nothing; get diagnostics n=ROW_COUNT; return n; end; $$;

revoke execute on function public.manage_reclass_session(uuid,smallint,time,time,text,boolean,text,text,uuid,uuid,text) from public,anon;
grant execute on function public.manage_reclass_session(uuid,smallint,time,time,text,boolean,text,text,uuid,uuid,text) to authenticated;
revoke execute on function public.cancel_reclass_session(uuid) from public,anon;
grant execute on function public.cancel_reclass_session(uuid) to authenticated;
revoke execute on function public.manage_reclass_session_occurrence(uuid,uuid,date,time,time,text,text,uuid,text) from public,anon;
grant execute on function public.manage_reclass_session_occurrence(uuid,uuid,date,time,time,text,text,uuid,text) to authenticated;
revoke execute on function public.generate_session_occurrences(uuid,date) from public,anon;
grant execute on function public.generate_session_occurrences(uuid,date) to authenticated;
