<script lang="ts">
  const { data, form } = $props();
  let roleId = $state(''); let teacherId = $state(''); let rightsAssignmentId = $state(''); let selectedRights = $state<string[]>([]); let operatorMember = $state(''); let operatorRole = $state('initiator'); let approvalLevel = $state(1);
  const toggleRight = (code: string) => selectedRights = selectedRights.includes(code) ? selectedRights.filter((r) => r !== code) : [...selectedRights, code];
  const rightsFor = (id: string) => data.rights.filter((r: any) => r.assignment_id === id).map((r: any) => r.right_code);
  function loadRights(id: string) { rightsAssignmentId = id; selectedRights = rightsFor(id); }
</script>
<svelte:head><title>ReClass committee roles & PayBill rights · eShule</title></svelte:head>
<div class="mx-auto max-w-6xl space-y-6 py-6 sm:py-8"><header class="rounded-3xl border border-border/60 bg-white p-6 shadow-card sm:p-8"><p class="text-xs font-bold uppercase tracking-[0.16em] text-primary">ReClass governance</p><h1 class="mt-2 text-3xl font-semibold tracking-tight text-ink-900">Committee roles & PayBill rights</h1><p class="mt-3 max-w-3xl text-sm leading-6 text-ink-500">The remedial committee has defined business roles. Admin assigns those roles to teachers; PayBill rights are an additional permission layer.</p></header>
{#if form?.message}<div role={form.success?'status':'alert'} class="rounded-xl border p-4 text-sm font-semibold {form.success?'border-emerald-200 bg-emerald-50 text-emerald-800':'border-red-200 bg-red-50 text-red-800'}">{form.message}</div>{/if}
<section class="grid gap-4 lg:grid-cols-3"><article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs font-bold uppercase text-slate-500">Committee roles</p><p class="mt-2 text-3xl font-bold text-slate-950">{data.roles.length}</p></article><article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs font-bold uppercase text-slate-500">Teacher assignments</p><p class="mt-2 text-3xl font-bold text-slate-950">{data.assignments.filter((a:any)=>a.active).length}</p></article><article class="rounded-2xl border {data.governance?.ready?'border-emerald-200 bg-emerald-50':'border-amber-200 bg-amber-50'} p-5 shadow-sm"><p class="text-xs font-bold uppercase text-slate-600">PayBill readiness</p><p class="mt-2 text-xl font-bold {data.governance?.ready?'text-emerald-800':'text-amber-800'}">{data.governance?.ready?'Ready':'Configuration incomplete'}</p><p class="mt-1 text-xs text-slate-600">{data.governance?.approval_levels_configured??0} / {data.governance?.required_approval_levels??1} approval levels configured.</p></article></section>
<section class="grid gap-6 lg:grid-cols-2"><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h2 class="text-lg font-bold text-slate-900">Assign committee role</h2><form method="POST" action="?/assignRole" class="mt-5 space-y-4"><label class="block text-sm font-semibold">Committee role<select name="role_id" bind:value={roleId} required class="field"><option value="">Select role</option>{#each data.roles as r}<option value={r.id}>{r.name}</option>{/each}</select></label><label class="block text-sm font-semibold">Teacher<select name="teacher_id" bind:value={teacherId} required class="field"><option value="">Select teacher</option>{#each data.teachers as t}<option value={t.id}>{t.full_name}{t.phone?` · ${t.phone}`:''}</option>{/each}</select></label><button class="button">Assign committee role</button></form></div>
<div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h2 class="text-lg font-bold text-slate-900">Add PayBill rights</h2>{#if data.assignments.length}<form method="POST" action="?/grantRights" class="mt-5 space-y-4"><label class="block text-sm font-semibold">Committee assignment<select name="assignment_id" bind:value={rightsAssignmentId} onchange={(e)=>loadRights((e.currentTarget as HTMLSelectElement).value)} required class="field"><option value="">Select assignment</option>{#each data.assignments.filter((a:any)=>a.active) as a}<option value={a.id}>{a.profiles?.full_name} · {a.remedial_committee_role_definitions?.name}</option>{/each}</select></label><input type="hidden" name="rights" value={selectedRights.join(',')}/><div class="grid gap-2 sm:grid-cols-2">{#each data.rightCatalog as right}<label class="flex min-h-10 items-center gap-2 rounded-lg border px-3 text-xs font-semibold"><input type="checkbox" checked={selectedRights.includes(right[0])} onchange={()=>toggleRight(right[0])}/>{right[1]}</label>{/each}</div><button class="button">Save additional rights</button></form>{:else}<div class="mt-5 rounded-xl border border-dashed p-8 text-center text-sm text-slate-500">Assign a committee role first.</div>{/if}</div></section>
<section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h2 class="text-base font-bold text-slate-900">PayBill operator layer</h2><form method="POST" action="?/assignOperator" class="mt-5 grid gap-4 lg:grid-cols-3"><label class="text-sm font-semibold">Committee member<select name="committee_member_id" bind:value={operatorMember} required class="field"><option value="">Select member</option>{#each data.assignments.filter((a:any)=>a.active) as a}<option value={a.id}>{a.profiles?.full_name} · {a.remedial_committee_role_definitions?.name}</option>{/each}</select></label><label class="text-sm font-semibold">PayBill role<select name="operator_role" bind:value={operatorRole} class="field"><option value="initiator">Initiator / maker</option><option value="approver">Approver / checker</option><option value="manager">Manager</option><option value="auditor">Auditor / read only</option></select></label>{#if operatorRole==='approver'}<label class="text-sm font-semibold">Approval level<select name="approval_level" bind:value={approvalLevel} class="field">{#each Array.from({length:Math.max(1,Number(data.settings.approval_levels??1))},(_,index)=>index+1) as level}<option value={level}>{level}</option>{/each}</select></label>{:else}<input type="hidden" name="approval_level" value=""/>{/if}<button class="button lg:col-span-3">Save PayBill operator assignment</button></form></section>
<section class="grid gap-6 lg:grid-cols-2"><div class="panel"><h2 class="panel-title">Assigned committee roles</h2><div class="mt-4 divide-y">{#if data.assignments.length===0}<p class="py-6 text-sm text-slate-500">No committee roles assigned.</p>{:else}{#each data.assignments as a (a.id)}<div class="flex items-center justify-between gap-3 py-3"><div><p class="text-sm font-semibold">{a.profiles?.full_name}</p><p class="text-xs text-slate-500">{a.remedial_committee_role_definitions?.name} · {a.active?'Active':'Inactive'}</p></div><span class="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-bold">Teacher</span></div>{/each}{/if}</div></div><div class="panel"><h2 class="panel-title">PayBill operator assignments</h2><div class="mt-4 divide-y">{#if data.operators.length===0}<p class="py-6 text-sm text-slate-500">No PayBill operators assigned.</p>{:else}{#each data.operators as op}<div class="flex items-center justify-between gap-3 py-3"><div><p class="text-sm font-semibold">{op.remedial_committee_members?.profiles?.full_name}</p><p class="text-xs text-slate-500">{op.operator_role}{op.approval_level?` · Level ${op.approval_level}`:''} · {op.active?'Active':'Inactive'}</p></div>{#if op.active}<form method="POST" action="?/deactivate"><input type="hidden" name="id" value={op.id}/><button class="text-xs font-semibold text-red-600 hover:underline">Deactivate</button></form>{/if}</div>{/each}{/if}</div></div></section></div>
<style>.field{margin-top:.5rem;display:block;min-height:2.75rem;width:100%;border:1px solid #e2e8f0;border-radius:.5rem;background:white;padding:0 .75rem}.button{min-height:2.75rem;width:100%;border-radius:.5rem;background:hsl(var(--primary));padding:0 1rem;font-size:.875rem;font-weight:700;color:hsl(var(--primary-foreground))}.panel{border:1px solid #e2e8f0;border-radius:1rem;background:white;padding:1.25rem;box-shadow:0 1px 2px rgba(0,0,0,.04)}.panel-title{font-size:1rem;font-weight:700;color:#0f172a}</style>
