<script lang="ts">
  const { data, form } = $props();
  const assignments: any[] = data.assignments ?? [];
  const operators: any[] = data.operators ?? [];
  let roleId = $state(''); let profileId = $state(''); let rightsAssignmentId = $state(''); let operatorRole = $state('initiator'); let approvalLevel = $state(1);
  const rightsFor = (id:string) => data.rights.filter((r:any) => r.assignment_id === id && r.active).map((r:any) => r.right_key);
</script>
<svelte:head><title>ReClass committee & PayBill governance · eShule</title></svelte:head>
<div class="mx-auto max-w-6xl space-y-6 py-6 sm:py-8">
  <header class="border-b border-slate-200 pb-6"><p class="text-xs font-bold uppercase tracking-[0.16em] text-primary">ReClass governance</p><h1 class="mt-2 text-3xl font-semibold tracking-tight text-slate-950">Committee & PayBill governance</h1><p class="mt-3 max-w-3xl text-sm leading-6 text-slate-500">Committee appointments, additional rights and PayBill maker/checker controls are enforced through the secured ReClass database workflow.</p></header>
  {#if form?.message}<div role={form.success?'status':'alert'} class="rounded-xl border p-4 text-sm font-semibold {form.success?'border-emerald-200 bg-emerald-50 text-emerald-800':'border-red-200 bg-red-50 text-red-800'}">{form.message}</div>{/if}
  <section class="grid gap-4 md:grid-cols-3"><div class="border-b border-slate-200 pb-4"><p class="text-xs font-bold uppercase text-slate-500">Defined roles</p><p class="mt-2 text-3xl font-bold text-slate-950">{data.roles.length}</p></div><div class="border-b border-slate-200 pb-4"><p class="text-xs font-bold uppercase text-slate-500">Active assignments</p><p class="mt-2 text-3xl font-bold text-slate-950">{assignments.filter((a:any)=>a.active).length}</p></div><div class="border-b border-slate-200 pb-4"><p class="text-xs font-bold uppercase text-slate-500">PayBill readiness</p><p class="mt-2 text-xl font-bold {data.governance?.ready?'text-emerald-700':'text-amber-700'}">{data.governance?.ready?'Ready':'Needs configuration'}</p></div></section>

  <section class="grid gap-6 lg:grid-cols-2">
    <div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6">
      <h2 class="text-lg font-bold text-slate-900">Assign committee role</h2><p class="mt-1 text-sm text-slate-500">Appointments use the authoritative ReClass committee assignment table.</p>
      <form method="POST" action="?/assignRole" class="mt-5 space-y-4">
        <label class="block text-sm font-semibold text-slate-700">Committee role<select name="role_id" bind:value={roleId} required class="mt-2 min-h-11 w-full rounded-lg border border-slate-200 bg-white px-3"><option value="">Select role</option>{#each data.roles as r}<option value={r.id}>{r.name}{r.description?` · ${r.description}`:''}</option>{/each}</select></label>
        <label class="block text-sm font-semibold text-slate-700">Teacher<select name="profile_id" bind:value={profileId} required class="mt-2 min-h-11 w-full rounded-lg border border-slate-200 bg-white px-3"><option value="">Select teacher</option>{#each data.teachers as t}<option value={t.id}>{t.full_name}{t.phone?` · ${t.phone}`:''}</option>{/each}</select></label>
        <div class="grid gap-4 sm:grid-cols-2"><label class="text-sm font-semibold text-slate-700">Effective from<input name="effective_from" type="date" value={new Date().toISOString().slice(0,10)} class="mt-2 min-h-11 w-full rounded-lg border border-slate-200 px-3"/></label><label class="text-sm font-semibold text-slate-700">Effective to<input name="effective_to" type="date" class="mt-2 min-h-11 w-full rounded-lg border border-slate-200 px-3"/></label></div>
        <label class="block text-sm font-semibold text-slate-700">Notes<textarea name="notes" rows="2" class="mt-2 w-full rounded-lg border border-slate-200 px-3 py-2" placeholder="Optional appointment note"></textarea></label>
        <button class="min-h-11 w-full rounded-lg bg-primary px-4 text-sm font-bold text-primary-foreground">Assign role</button>
      </form>
    </div>
    <div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6">
      <h2 class="text-lg font-bold text-slate-900">PayBill configuration</h2><p class="mt-1 text-sm text-slate-500">Maker/checker is mandatory for multi-level approval workflows.</p>
      {#if data.settings?.id}<form method="POST" action="?/saveSettings" class="mt-5 space-y-4"><input type="hidden" name="id" value={data.settings.id}/><label class="block text-sm font-semibold text-slate-700">PayBill number<input name="paybill_number" value={data.settings.paybill_number ?? ''} class="mt-2 min-h-11 w-full rounded-lg border border-slate-200 px-3"/></label><label class="block text-sm font-semibold text-slate-700">Account prefix<input name="account_prefix" value={data.settings.account_prefix ?? ''} class="mt-2 min-h-11 w-full rounded-lg border border-slate-200 px-3"/></label><label class="block text-sm font-semibold text-slate-700">Approval levels<select name="approval_levels" class="mt-2 min-h-11 w-full rounded-lg border border-slate-200 px-3">{#each [1,2,3,4,5] as level}<option value={level} selected={Number(data.settings.approval_levels ?? 1)===level}>{level}</option>{/each}</select></label><div class="rounded-lg bg-slate-50 p-3 text-xs text-slate-600">Minimum web operators: <strong>{data.settings.minimum_web_operators ?? 1}</strong>. Initiator self-approval: <strong>No</strong>.</div><button class="min-h-11 w-full rounded-lg bg-slate-900 px-4 text-sm font-bold text-white">Save configuration</button></form>{:else}<p class="mt-6 rounded-xl border border-dashed border-slate-200 p-6 text-sm text-slate-500">PayBill settings have not been initialized.</p>{/if}
    </div>
  </section>

  <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6">
    <div class="flex flex-wrap items-end justify-between gap-3"><div><h2 class="text-lg font-bold text-slate-900">Active committee assignments</h2><p class="mt-1 text-sm text-slate-500">Rights are managed individually and disappear when an assignment ends.</p></div></div>
    <div class="mt-4 divide-y divide-slate-100">{#if assignments.length===0}<p class="py-6 text-sm text-slate-500">No committee assignments yet.</p>{:else}{#each assignments as a (a.id)}<div class="flex flex-wrap items-center justify-between gap-4 py-4"><div><p class="font-semibold text-slate-900">{a.profile?.full_name ?? 'Unknown teacher'}</p><p class="text-xs text-slate-500">{a.role?.name ?? 'Committee role'} · From {a.effective_from}{a.effective_to?` · To ${a.effective_to}`:''}</p></div>{#if a.active}<form method="POST" action="?/endAssignment" class="flex items-center gap-2"><input type="hidden" name="id" value={a.id}/><input name="effective_to" type="date" class="h-9 rounded-lg border border-slate-200 px-2 text-xs"/><button class="text-xs font-semibold text-red-600 hover:underline">End assignment</button></form>{:else}<span class="text-xs font-semibold text-slate-400">Inactive</span>{/if}</div>{/each}{/if}</div>
  </section>

  <section class="grid gap-6 lg:grid-cols-2">
    <div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h2 class="text-lg font-bold text-slate-900">Committee rights</h2><p class="mt-1 text-sm text-slate-500">Financial rights are restricted by the database role matrix.</p>{#if assignments.filter((a:any)=>a.active).length}<div class="mt-4 space-y-4">{#each assignments.filter((a:any)=>a.active) as a}<div class="border-b border-slate-100 pb-4"><div class="mb-2"><p class="text-sm font-semibold">{a.profile?.full_name}</p><p class="text-xs text-slate-500">{a.role?.name}</p></div><div class="grid gap-2 sm:grid-cols-2">{#each data.rightCatalog as right}<form method="POST" action="?/grantRight"><input type="hidden" name="assignment_id" value={a.id}/><input type="hidden" name="right_key" value={right[0]}/><input type="hidden" name="granted" value={rightsFor(a.id).includes(right[0])?'false':'true'}/><button class="flex min-h-9 w-full items-center justify-between rounded-lg border px-3 text-left text-xs font-semibold {rightsFor(a.id).includes(right[0])?'border-primary/40 bg-primary/5 text-primary':'border-slate-200 text-slate-600'}"><span>{right[1]}</span><span>{rightsFor(a.id).includes(right[0])?'Granted':'Grant'}</span></button></form>{/each}</div></div>{/each}</div>{:else}<p class="mt-6 text-sm text-slate-500">Assign a committee role first.</p>{/if}</div>
    <div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h2 class="text-lg font-bold text-slate-900">PayBill operators</h2><p class="mt-1 text-sm text-slate-500">Each operator must belong to an active committee assignment.</p><form method="POST" action="?/assignOperator" class="mt-5 space-y-4"><label class="block text-sm font-semibold text-slate-700">Committee assignment<select name="role_assignment_id" required class="mt-2 min-h-11 w-full rounded-lg border border-slate-200 px-3"><option value="">Select assignment</option>{#each assignments.filter((a:any)=>a.active) as a}<option value={a.id}>{a.profile?.full_name} · {a.role?.name}</option>{/each}</select></label><div class="grid gap-4 sm:grid-cols-2"><label class="text-sm font-semibold">Operator role<select name="operator_role" bind:value={operatorRole} class="mt-2 min-h-11 w-full rounded-lg border border-slate-200 px-3"><option value="initiator">Initiator</option><option value="approver">Approver</option><option value="manager">Manager</option><option value="auditor">Auditor</option></select></label>{#if operatorRole==='approver'}<label class="text-sm font-semibold">Approval level<select name="approval_level" bind:value={approvalLevel} class="mt-2 min-h-11 w-full rounded-lg border border-slate-200 px-3">{#each Array.from({length:Math.max(1,Number(data.settings?.approval_levels??1))},(_,i)=>i+1) as level}<option value={level}>{level}</option>{/each}</select></label>{:else}<input type="hidden" name="approval_level" value="1"/>{/if}</div><button class="min-h-11 w-full rounded-lg bg-primary px-4 text-sm font-bold text-primary-foreground">Assign operator</button></form><div class="mt-6 divide-y divide-slate-100">{#each operators as op}<div class="flex items-center justify-between gap-3 py-3"><div><p class="text-sm font-semibold">{op.profile?.full_name ?? 'Unknown teacher'}</p><p class="text-xs text-slate-500">{op.operator_role}{op.approval_level?` · Level ${op.approval_level}`:''} · {op.active?'Active':'Inactive'}</p></div>{#if op.active}<form method="POST" action="?/deactivateOperator"><input type="hidden" name="id" value={op.id}/><button class="text-xs font-semibold text-red-600 hover:underline">Deactivate</button></form>{/if}</div>{/each}</div></div>
  </section>
</div>
